export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST'
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS'
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL'
export const UPLOAD_PHOTO_RESET = 'UPLOAD_PHOTO_RESET'

export const GET_ITEM_PHOTOS_REQUEST = 'GET_ITEM_PHOTOS_REQUEST'
export const GET_ITEM_PHOTOS_SUCCESS = 'GET_ITEM_PHOTOS_SUCCESS'
export const GET_ITEM_PHOTOS_FAIL = 'GET_ITEM_PHOTOS_FAIL'
export const GET_ITEM_PHOTOS_RESET = 'GET_ITEM_PHOTOS_RESET'
