export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST'
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS'
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL'
export const UPLOAD_PHOTO_RESET = 'UPLOAD_PHOTO_RESET'

export const GET_ITEM_PHOTOS_REQUEST = 'GET_ITEM_PHOTOS_REQUEST'
export const GET_ITEM_PHOTOS_SUCCESS = 'GET_ITEM_PHOTOS_SUCCESS'
export const GET_ITEM_PHOTOS_FAIL = 'GET_ITEM_PHOTOS_FAIL'
export const GET_ITEM_PHOTOS_RESET = 'GET_ITEM_PHOTOS_RESET'

export const DELETE_ITEM_PHOTO_REQUEST = 'DELETE_ITEM_PHOTO_REQUEST'
export const DELETE_ITEM_PHOTO_SUCCESS = 'DELETE_ITEM_PHOTO_SUCCESS'
export const DELETE_ITEM_PHOTO_FAIL = 'DELETE_ITEM_PHOTO_FAIL'
export const DELETE_ITEM_PHOTO_RESET = 'DELETE_ITEM_PHOTO_RESET'

export const UPLOAD_ORDER_RECEIPT_REQUEST = 'UPLOAD_ORDER_RECEIPT_REQUEST'
export const UPLOAD_ORDER_RECEIPT_SUCCESS = 'UPLOAD_ORDER_RECEIPT_SUCCESS'
export const UPLOAD_ORDER_RECEIPT_FAIL = 'UPLOAD_ORDER_RECEIPT_FAIL'
export const UPLOAD_ORDER_RECEIPT_RESET = 'UPLOAD_ORDER_RECEIPT_RESET'

export const GET_ORDER_RECEIPT_REQUEST = 'GET_ORDER_RECEIPT_REQUEST'
export const GET_ORDER_RECEIPT_SUCCESS = 'GET_ORDER_RECEIPT_SUCCESS'
export const GET_ORDER_RECEIPT_FAIL = 'GET_ORDER_RECEIPT_FAIL'
export const GET_ORDER_RECEIPT_RESET = 'GET_ORDER_RECEIPT_RESET'

export const DELETE_ORDER_RECEIPT_REQUEST = 'DELETE_ORDER_RECEIPT_REQUEST'
export const DELETE_ORDER_RECEIPT_SUCCESS = 'DELETE_ORDER_RECEIPT_SUCCESS'
export const DELETE_ORDER_RECEIPT_FAIL = 'DELETE_ORDER_RECEIPT_FAIL'
export const DELETE_ORDER_RECEIPT_RESET = 'DELETE_ORDER_RECEIPT_RESET'
