export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

export const ORDER_ADD_ITEM_REQUEST = 'ORDER_ADD_ITEM_REQUEST'
export const ORDER_ADD_ITEM_SUCCESS = 'ORDER_ADD_ITEM_SUCCESS'
export const ORDER_ADD_ITEM_FAIL = 'ORDER_ADD_ITEM_FAIL'
export const ORDER_ADD_ITEM_RESET = 'ORDER_ADD_ITEM_RESET'

export const ORDER_DELETE_ITEM_REQUEST = 'ORDER_DELETE_ITEM_REQUEST'
export const ORDER_DELETE_ITEM_SUCCESS = 'ORDER_DELETE_ITEM_SUCCESS'
export const ORDER_DELETE_ITEM_FAIL = 'ORDER_DELETE_ITEM_FAIL'
