export const PLACE_AUTOCOMPLETE_REQUEST = 'PLACE_AUTOCOMPLETE_REQUEST'
export const PLACE_AUTOCOMPLETE_SUCCESS = 'PLACE_AUTOCOMPLETE_SUCCESS'
export const PLACE_AUTOCOMPLETE_FAIL = 'PLACE_AUTOCOMPLETE_FAIL'

export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'

export const REQUEST_PICKUP_REQUEST = 'REQUEST_PICKUP_REQUEST'
export const REQUEST_PICKUP_SUCCESS = 'REQUEST_PICKUP_SUCCESS'
export const REQUEST_PICKUP_FAIL = 'REQUEST_PICKUP_FAIL'

export const PICKUP_HISTORY_REQUEST = 'PICKUP_HISTORY_REQUEST'
export const PICKUP_HISTORY_SUCCESS = 'PICKUP_HISTORY_SUCCESS'
export const PICKUP_HISTORY_FAIL = 'PICKUP_HISTORY_FAIL'
