export const GET_MY_ROUTE_REQUEST = 'GET_MY_ROUTE_REQUEST'
export const GET_MY_ROUTE_SUCCESS = 'GET_MY_ROUTE_SUCCESS'
export const GET_MY_ROUTE_FAIL = 'GET_MY_ROUTE_FAIL'
export const GET_MY_ROUTE_RESET = 'GET_MY_ROUTE_RESET'

export const CREATE_MY_ROUTE_REQUEST = 'CREATE_MY_ROUTE_REQUEST'
export const CREATE_MY_ROUTE_SUCCESS = 'CREATE_MY_ROUTE_SUCCESS'
export const CREATE_MY_ROUTE_FAIL = 'CREATE_MY_ROUTE_FAIL'

export const DELETE_MY_ROUTE_REQUEST = 'DELETE_MY_ROUTE_REQUEST'
export const DELETE_MY_ROUTE_SUCCESS = 'DELETE_MY_ROUTE_SUCCESS'
export const DELETE_MY_ROUTE_FAIL = 'DELETE_MY_ROUTE_FAIL'
