export const GET_MY_ROUTE_REQUEST = 'GET_MY_ROUTE_REQUEST'
export const GET_MY_ROUTE_SUCCESS = 'GET_MY_ROUTE_SUCCESS'
export const GET_MY_ROUTE_FAIL = 'GET_MY_ROUTE_FAIL'
export const GET_MY_ROUTE_RESET = 'GET_MY_ROUTE_RESET'

export const CREATE_MY_ROUTE_REQUEST = 'CREATE_MY_ROUTE_REQUEST'
export const CREATE_MY_ROUTE_SUCCESS = 'CREATE_MY_ROUTE_SUCCESS'
export const CREATE_MY_ROUTE_FAIL = 'CREATE_MY_ROUTE_FAIL'

export const DELETE_MY_ROUTE_REQUEST = 'DELETE_MY_ROUTE_REQUEST'
export const DELETE_MY_ROUTE_SUCCESS = 'DELETE_MY_ROUTE_SUCCESS'
export const DELETE_MY_ROUTE_FAIL = 'DELETE_MY_ROUTE_FAIL'

export const GET_ACTIVE_ROUTES_REQUEST = 'GET_ACTIVE_ROUTES_REQUEST'
export const GET_ACTIVE_ROUTES_SUCCESS = 'GET_ACTIVE_ROUTES_SUCCESS'
export const GET_ACTIVE_ROUTES_FAIL = 'GET_ACTIVE_ROUTES_FAIL'
export const GET_ACTIVE_ROUTES_RESET = 'GET_ACTIVE_ROUTES_RESET'

export const GET_ROUTE_ITEMS_REQUEST = 'GET_ROUTE_ITEMS_REQUEST'
export const GET_ROUTE_ITEMS_SUCCESS = 'GET_ROUTE_ITEMS_SUCCESS'
export const GET_ROUTE_ITEMS_FAIL = 'GET_ROUTE_ITEMS_FAIL'
export const GET_ROUTE_ITEMS_RESET = 'GET_ROUTE_ITEMS_RESET'

export const ROUTE_FINISH_REQUEST = 'ROUTE_FINISH_REQUEST'
export const ROUTE_FINISH_SUCCESS = 'ROUTE_FINISH_SUCCESS'
export const ROUTE_FINISH_FAIL = 'ROUTE_FINISH_FAIL'
export const ROUTE_FINISH_RESET = 'ROUTE_FINISH_RESET'
